import { NextResponse } from "next/server";
import JSZip from "jszip";
import { requireUser } from "@/lib/auth";
import { canUseFeature, spendCredits } from "@/lib/credits";
import { createServiceRoleClient } from "@/lib/supabase/server";

export async function POST(request: Request) {
  const { user, response } = await requireUser();
  if (response) return response;

  const { projectId, format } = (await request.json()) as {
    projectId: string;
    format: "zip" | "react" | "nextjs";
  };
  if (!projectId) {
    return NextResponse.json({ message: "projectId is required." }, { status: 400 });
  }

  // Export is always free of credits, but ZIP/React/Next.js export is still a
  // plan feature (locked on Free), per the spec's plan feature table.
  const gate = await canUseFeature(user!.id, "export_code");
  if (!gate.allowed) {
    return NextResponse.json({ message: gate.message }, { status: 403 });
  }

  const supabase = createServiceRoleClient();
  const { data: project } = await supabase
    .from("projects")
    .select("id, name, description, user_id, seo_title, seo_description, seo_og_image_url")
    .eq("id", projectId)
    .single();

  if (!project || project.user_id !== user!.id) {
    return NextResponse.json({ message: "Project not found." }, { status: 404 });
  }

  const { data: version } = await supabase
    .from("project_versions")
    .select("files")
    .eq("project_id", projectId)
    .order("version", { ascending: false })
    .limit(1)
    .single();

  if (!version) {
    return NextResponse.json({ message: "Nothing to export yet." }, { status: 404 });
  }

  const zip = new JSZip();
  const files = version.files as Record<string, string>;
  const isNextProject = format === "nextjs";

  const seoTitle = project.seo_title || project.name;
  const seoDescription = project.seo_description || project.description || "";

  for (const [path, content] of Object.entries(files)) {
    const target = isNextProject ? `src/app/${path}` : `src/${path}`;
    zip.file(target, content);
  }

  if (isNextProject) {
    // A real metadata export, not a placeholder — this is what makes the SEO
    // settings the customer configured actually ship in the exported project,
    // rather than only living in webma's own database.
    zip.file(
      "src/app/layout.tsx",
      `import type { Metadata } from "next";

export const metadata: Metadata = {
  title: ${JSON.stringify(seoTitle)},
  description: ${JSON.stringify(seoDescription)},
  ${project.seo_og_image_url ? `openGraph: { images: [${JSON.stringify(project.seo_og_image_url)}] },` : ""}
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`
    );
  } else {
    zip.file(
      "index.html",
      `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>${seoTitle}</title>
    <meta name="description" content="${seoDescription}" />
    ${project.seo_og_image_url ? `<meta property="og:image" content="${project.seo_og_image_url}" />` : ""}
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`
    );
  }

  zip.file(
    "package.json",
    JSON.stringify(
      {
        name: project.name.toLowerCase().replace(/\s+/g, "-"),
        version: "0.1.0",
        private: true,
        scripts: isNextProject
          ? { dev: "next dev", build: "next build", start: "next start" }
          : { dev: "vite", build: "vite build", preview: "vite preview" },
        dependencies: { react: "^18.3.1", "react-dom": "^18.3.1", ...(isNextProject ? { next: "^14.2.5" } : {}) },
      },
      null,
      2
    )
  );

  zip.file(
    "README.md",
    `# ${project.name}\n\nGenerated by webma — built by Techtig.\n\n## Getting started\n\n\`\`\`\nnpm install\nnpm run dev\n\`\`\`\n`
  );

  const buffer = await zip.generateAsync({ type: "nodebuffer" });

  // Export costs 0 credits, but the ledger entry still records that the action happened.
  await spendCredits(user!.id, "export_code", { isAdmin: gate.isAdmin, projectId });

  return new NextResponse(buffer, {
    status: 200,
    headers: {
      "Content-Type": "application/zip",
      "Content-Disposition": `attachment; filename="${project.name}-${format}.zip"`,
    },
  });
}
